In [ ]:
import pandas as pd

df = pd.DataFrame({
    "name": ["A", "B", "C"],
    "age": [20, 21, 22],
    "cgpa": [3.5, 3.7, 3.9]
})
df

In [ ]:
df.head()
df.tail()
df.shape        # (rows, cols)
df.columns
df.dtypes
# df.info()
# df.describe()
df

In [ ]:
df["age"]
# df[["age","cgpa"]]

In [ ]:
df.iloc[1:3]

In [ ]:
df["passed"]=df["cgpa"]>3.8
df.loc[3]
df

In [23]:
more_rows = pd.DataFrame({
    "name": ["T", "Cr"],
    "age": [21, 20],
    "cgpa": [4.0, 3.8]
})
df= pd.concat([df,more_rows],ignore_index=True)
df

   name  age  cgpa passed
0     A   20   3.5  False
1     B   21   3.7  False
2     C   22   3.9   True
3     D   23   4.0    NaN
4     E   24   3.8    NaN
5     D   23   4.0    NaN
6     E   24   3.8    NaN
7     T   21   4.0    NaN
8    Cr   20   3.8    NaN
9     T   21   4.0    NaN
10   Cr   20   3.8    NaN

In [24]:
df.groupby("age")["cgpa"].mean()

age
20    3.7
21    3.9
22    3.9
23    4.0
24    3.8
Name: cgpa, dtype: float64

In [25]:
df.groupby("age").agg({
    "cgpa": ["mean", "max"],
    "name": "count"
})

    cgpa       name
    mean  max count
age
20   3.7  3.8     3
21   3.9  4.0     3
22   3.9  3.9     1
23   4.0  4.0     2
24   3.8  3.8     2