In [3]:
import pandas as pd
print(pd.__version__)

2.1.4

In [4]:
inventory = pd.DataFrame({
    'Item': ['Apple', 'Banana', 'Orange'],
    'Quantity': [50, 100, 75],
    'Price': [0.5, 0.3, 0.8]
})

print(inventory['Quantity'])

0     50
1    100
2     75
Name: Quantity, dtype: int64

In [5]:
print(inventory.iloc[2])
print(inventory.loc[1,'Price'])
print(inventory[inventory['Price']<=0.5])

Item        Orange
Quantity        75
Price          0.8
Name: 2, dtype: object
0.3
     Item  Quantity  Price
0   Apple        50    0.5
1  Banana       100    0.3

In [6]:
inventory['IsExpensive']= inventory['Price']>0.6
inventory['TotalSum']= inventory['Price']*inventory['Quantity']
inventory = inventory.rename(columns={'TotalSum':'Total'})

In [7]:
import numpy as np
import pandas as pd

# Creating a fresh inventory to be sure we're on the same page
inventory = pd.DataFrame({
    'Product_Name': ['Apple', 'Banana', 'Orange', 'Grapes'],
    'Quantity': [50, np.nan, 75, 120],
    'Price': [0.5, 0.3, 0.8, np.nan]
})

In [8]:
inventory['Quantity']= inventory['Quantity'].fillna(0)
inventory.dropna(subset=['Price'],inplace=True)

In [9]:
inventory['Quantity'].sum()

125.0

In [10]:
df = pd.DataFrame({'A': [1, None, 3], 'B': [4, 5, None],'C':[2,3,4]})
df

     A    B  C
0  1.0  4.0  2
1  NaN  5.0  3
2  3.0  NaN  4

In [11]:
df.isna().any()

A     True
B     True
C    False
dtype: bool

In [14]:

# Remove columns with any null values
df_clean = df.dropna(axis=1)
print(df_clean)
#    C
# 0  2
# 1  3
# 2  4nplace=True)
df

    name  age
0  alice  3.0
1    bob  4.0

    name  age
0  alice  3.0
1    bob  4.0

In [15]:
df = pd.DataFrame({
    'A': [1, None, 3],
    'B': [4, 5, None],
    'C': [2, 3, 4]
})

# Remove columns with any null values
df_clean = df.dropna(axis=1)
print(df_clean)
#    C
# 0  2
# 1  3
# 2  4

   C
0  2
1  3
2  4

In [21]:
import pandas as pd
import numpy as np

# A slightly more realistic dataset for a CSE student
data = {
    'Student': ['Abid', 'Sifat', 'Nuzhat', 'Muntasir', 'Fariha', 'Tanvir'],
    'Dept': ['CSE', 'CSE', 'EEE', 'CSE', 'EEE', 'ME'],
    'CGPA': [3.8, 3.9, 3.5, 3.2, 3.7, 3.0],
    'Credits_Completed': [100, 110, 90, 120, 85, 70]
}

df = pd.DataFrame(data)

# # 1. Grouping by Dept and finding the average CGPA
# avg_cgpa = df.groupby('Dept')['CGPA'].mean()
df.groupby('Dept')['CGPA'].mean()

# # 2. Getting multiple stats at once using .agg()
# # This is much cleaner than doing them one by one
# dept_stats = df.groupby('Dept').agg({
#     'CGPA': 'mean',
#     'Credits_Completed': 'sum',
#     'Student': 'count'
# })

# print("Average CGPA per Dept:")
# print(avg_cgpa)
# print("\nDetailed Department Stats:")
# print(dept_stats)

Dept
CSE    3.633333
EEE    3.600000
ME     3.000000
Name: CGPA, dtype: float64

In [13]:
df.to_html('myfile.html')